#!/bin/bash
wget http://slate.ucsc.edu/~brant/super-resolution/cutout-HSC-I-9813-pdr2_dud-210317-161628.fits
wget http://slate.ucsc.edu/~brant/super-resolution/hlsp_candels_hst_acs_cos-tot_f814w_v1.0_drz.fits
